server:
  port: 8089
spring:
  application:
    name: app
  datasource:
    url: jdbc:mysql://some-mysql:6033/db_test
    username: app
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 1
      timeout: 30s
      password:
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms

auth:
  token:
    expire-time: 30000
    secret: abcdefghijklmnopqrstuvwxyz
    header: Authorization
  ignored:
    urls:
      - /auth/login