server:
  port: 8089
spring:
  application:
    name: app
  datasource:
    url: jdbc:mysql://some-mysql:6033/db_test
    username: app
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


auth:
  token:
    expire-time: 30000
    secret: abcdefghijklmnopqrstuvwxyz
    header: Authorization
  ignored:
    urls:
      - /auth/login